### PR TITLE
july 2016

### PR DESCRIPTION
**Pull request by toetoetoetoetoe**
adding july 2016 data

### CODE REVIEW

**Comment by sgentle** [comment]
Appreciate the PR! Times are in UTC, so 06:00 would be 4pm. Happy to merge other than that though. :)

**Comment by toetoetoetoetoe** [comment]
My bad. Should reflect the time better now :)

**Comment by sgentle** [comment]
👍

**Comment by sgentle** [comment]
Oh rofl. It was also set to 2016-07-18, but I assume it's... uh, 2016-07-20?

**Comment by sgentle** [comment]
I should learn to read more carefully. 😄

**Comment by toetoetoetoetoe** [comment]
Whoops, missed this. That would have been when I was undoing a previous error. Probably not worth patching it up now. I'll get it right next month tho lol :)

**Pull request merged**
