### PR TITLE
Fill the gaps till the end of 2015

### PR DESCRIPTION
**Pull request by koresar**
On the last meetup they said that the event will be one week later, on the 28-th of October.

### CODE REVIEW

**Comment by koresar** [comment]
Btw, thank you for the most reliable schedule site in the world!

**Comment by sgentle** [comment]
Thanks for the pull request!

Are those dates all confirmed? My philosophy is that it's better to say "I don't (fucking) know" than an incorrect date, so that's why I've been only filling them in as they are announced.

**Comment by koresar** [comment]
Only the October one is confirmed. Should I change?

**Comment by sgentle** [comment]
Oh, sorry, I totally forgot about this. Yes please!

**Comment by koresar** [comment]
@sgentle done

**Pull request merged**
